### ISSUE TITLE
user.borrowItem creates the item two times

### ISSUE THREAD

**Issue by felunka** [VSETH-GECO/GECo4J#7]
When you create a new borrowed item for a user with user.borrowItem("name"), the api will save the Item twice.

**Comment by davue** [comment]
Should be fixed since a51adba47c8f2b0abe98f1889b00df5c559a32bb, I will look into it.

**Comment by davue** [comment]
I couldn't reproduce the double borrowing, neither using the Reactor nor using the Android compatible HTTP client. But I found some other bugs along the way, which I fixed. Try using this version 5ad91c651f7f34c2183850a51a83a774ce9c6746 and tell me if the bug still exists.
